{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cooked.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cooked.labels" . | nindent 4 }}
  {{- $ann := include "cooked.annotations" . }}
  {{- if or $ann .Values.serviceAccount.annotations }}
  annotations:
    {{- with $ann }}
    {{- . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
