apiVersion: v2
name: cooked
description: A rendering proxy for air-gapped environments — fetches raw documents and serves styled HTML
type: application
version: 1.4.1 # x-release-please-version
appVersion: "1.4.1" # x-release-please-version
kubeVersion: ">=1.22.0"
home: https://github.com/air-gapped/cooked
sources:
  - https://github.com/air-gapped/cooked
keywords:
  - rendering
  - proxy
  - markdown
  - asciidoc
  - air-gapped
maintainers:
  - name: air-gapped
    url: https://github.com/air-gapped
